module.exports = {
  about: 'Essa aplicação tem como fim, ajudar pessoas que podem estar com necessidade de mantimentos ou medicamentos durante a pandemia que ocorre no mundo. Tendo o objetivo dela claro, deve ser suficiente o entendimento e o público que ela espera. Como todos sabemos, nem todas as pessoas têm condições de ficar inoperantes por tempo indeterminado, embora se deva ter ciência que se puder ficar em casa, é o melhor a se fazer. Neste espaço, toda e qualquer pessoa poderá pedir ajuda, seja por temor a algum sintoma recorrente do vírus, ou falta de alimento, abandono, violência e assim respectivamente. Acredito que sempre haverá alguém disposto a ajudar, o intuito é encurtar esse caminho, utilizando a tecnologia para criar essa ponte, já que não podemos estar em pleno movimento, por fim, tenham consciência e pleno entendimento da utilização desta ferramenta. E, também, serve para denúncias sobre abandono de animais! Vale lembrar: Animais não passam coronavirus para humanos :)',
  instructionForUse:"Ao se cadastrar, um ID (Identidade), será gerado para você, equivale a um cadastro comum, como email e senha, anote esse ID em algum lugar, pois não terá como recuperar, uma vez que se perca. A aplicação na Web só funciona para cadastro dos casos, ou seja, se você souber de algum caso e quer pedir ajuda é só cadastrar e dar as informações necessárias, seja conciso, para que outras pessoas possam ajudar. No aplicativo mobile (celulares em geral), é onde quem quer somente ajudar poderá ver os casos registrados e, assim, se caso haja interesse, você poderá entrar em contato diretamente com quem cadastrou o pedido de ajuda. No app mobile, não haverá necessidade alguma de registro.",
  userPrivacy: 'Todos os dados inseridos nessa plataforma estão seguros, para proteger ainda mais o usuário, utilizei um “id”, ou seja, identidade, ao se cadastrar na plataforma um ID será gerado, números aleatórios que não correm o menor risco de ser descoberto. Assim, não sendo necessário colocar senhas ou outros dados, o admin por trás do app, não terá acesso a essas informações, são todas criptografadas assim que o registro é feito na plataforma.',
  userStatements: 'Quanto a alguma tentativa de uso inadequado da plataforma, como estamos lidando com usuários reais, partners de segurança foram adotados para controle e monitoramento, mas sempre acreditando nas pessoas, torçamos que não haja alguma tentativa de golpe e outros.',
  instalationGuides: 'Por hora, a aplicação funcionará somente em Android! Como é um projeto sem qualquer tipo de fim lucrativo, não hospedarei nas lojas de aplicativos. Baixe a APK, no seu android vá até “Configurações”, depois vá até “Segurança” e encontre a opção “FONTES DESCONHECIDAS”, ative! Depois disso é só instalar e aguardar.',
  doubtAboutUse: 'Se você ficou com dúvidas de como usar a plataforma web, assista esse vídeo aqui:',
  doubtMobileUsage: 'Veja como funciona a aplicação mobile:',
  thanks: 'Agradecimento a Diego, pelo empenho em criar um projeto open source que possibilita expandar em ideias e conhecimento.'
}